services:
  db:
    restart: always
    image: postgres:17.2-alpine
    environment:
      POSTGRES_DB: ${DB_CONFIG__DB_NAME}
      POSTGRES_USER: ${DB_CONFIG__DB_USER}
      POSTGRES_PASSWORD: ${DB_CONFIG__DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data 
    env_file:
      - src/.env
    ports:
      - "${DB_CONFIG__DB_PORT}:5432"

  test_db:
    restart: always
    image: postgres:17.2-alpine
    environment:
      POSTGRES_DB: ${TEST_DB_CONFIG__DB_NAME}
      POSTGRES_USER: ${TEST_DB_CONFIG__DB_USER}      
      POSTGRES_PASSWORD: ${TEST_DB_CONFIG__DB_PASSWORD}
    ports:
      - "${TEST_DB_CONFIG__DB_PORT}:5432"


volumes:
  pgdata:
