FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1\
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./
COPY scripts/run_migrations.sh ./run_migrations.sh
RUN chmod +x /app/run_migrations.sh


ENV PYTHONPATH=/app

CMD ["sh", "./run_migrations.sh"]