"""add UserToken model

Revision ID: 89cbc79c5bc2
Revises: c2db9a37a561
Create Date: 2025-06-22 16:18:11.826765

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89cbc79c5bc2"
down_revision: Union[str, None] = "c2db9a37a561"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usertokens",
        sa.Column("user_uuid", sa.Uuid(), nullable=True),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "token_type",
            sa.Enum(
                "REFRESH",
                "EMAIL_VERIFICATION",
                "PASSWORD_RESET",
                name="tokentype",
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("ip_adress", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["users.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_usertokens_expires_at"),
        "usertokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_usertokens_token_hash"),
        "usertokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_usertokens_token_type"),
        "usertokens",
        ["token_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_usertokens_user_uuid"),
        "usertokens",
        ["user_uuid"],
        unique=False,
    )
    op.alter_column(
        "tasks", "team_uuid", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint("tasks_team_uuid_fkey", "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "teams", ["team_uuid"], ["uuid"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        "tasks_team_uuid_fkey",
        "tasks",
        "teams",
        ["team_uuid"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "tasks", "team_uuid", existing_type=sa.UUID(), nullable=False
    )
    op.drop_index(op.f("ix_usertokens_user_uuid"), table_name="usertokens")
    op.drop_index(op.f("ix_usertokens_token_type"), table_name="usertokens")
    op.drop_index(op.f("ix_usertokens_token_hash"), table_name="usertokens")
    op.drop_index(op.f("ix_usertokens_expires_at"), table_name="usertokens")
    op.drop_table("usertokens")
    # ### end Alembic commands ###
