"""add foreignkey from User to Team

Revision ID: c2db9a37a561
Revises: 6769a12e6018
Create Date: 2025-06-11 13:45:01.620962

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c2db9a37a561"
down_revision: Union[str, None] = "6769a12e6018"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "evaluations", ["uuid"])
    op.create_unique_constraint(None, "meetings", ["uuid"])
    op.create_unique_constraint(None, "tasks", ["uuid"])
    op.create_unique_constraint(None, "teams", ["uuid"])
    op.add_column("users", sa.Column("team_uuid", sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, "users", ["uuid"])
    op.create_foreign_key(
        None, "users", "teams", ["team_uuid"], ["uuid"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "team_uuid")
    op.drop_constraint(None, "teams", type_="unique")
    op.drop_constraint(None, "tasks", type_="unique")
    op.drop_constraint(None, "meetings", type_="unique")
    op.drop_constraint(None, "evaluations", type_="unique")
    # ### end Alembic commands ###
