"""fix ip_address column name in user_tokens

Revision ID: 5a43d5e4e42e
Revises: 89cbc79c5bc2
Create Date: 2025-06-22 16:24:16.852195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a43d5e4e42e"
down_revision: Union[str, None] = "89cbc79c5bc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usertokens",
        sa.Column("ip_address", sa.String(length=45), nullable=True),
    )
    op.alter_column(
        "usertokens", "user_uuid", existing_type=sa.UUID(), nullable=False
    )
    op.create_unique_constraint(None, "usertokens", ["uuid"])
    op.drop_column("usertokens", "ip_adress")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usertokens",
        sa.Column(
            "ip_adress",
            sa.VARCHAR(length=45),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "usertokens", type_="unique")
    op.alter_column(
        "usertokens", "user_uuid", existing_type=sa.UUID(), nullable=True
    )
    op.drop_column("usertokens", "ip_address")
    # ### end Alembic commands ###
