name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: load code
        uses: actions/checkout@v4

      - name: download python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: download poetry
        run: pip install poetry

      - name: download dependencies
        run: poetry install

      - name: start Tests
        run: |
          cd src
          poetry run pytest -v